name: release
on:
  push:
    branches:
      - master
  # TODO: uncomment before merging
  pull_request:

jobs:
  # TODO: uncomment before merging
  # stable:
  #   uses: the-guild-org/shared-config/.github/workflows/release-stable.yml@main
  #   with:
  #     releaseScript: release
  #     nodeVersion: 18
  #     packageManagerVersion: modern
  #   secrets:
  #     githubToken: ${{ secrets.GITHUB_TOKEN }}
  #     npmToken: ${{ secrets.NODE_AUTH_TOKEN }}

  serve-with-hive-docker-image:
    # needs: stable
    # TODO: uncomment before merging
    # if: needs.stable.outputs.published == 'true'
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Create Docker Buildx builder
        run: docker buildx create --name mybuilder --use

      - name: Inspect Docker Buildx builder
        run: docker buildx inspect --bootstrap

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ardatan
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image for local testing
        id: build-single
        uses: docker/build-push-action@v6
        with:
          context: ./docker
          push: false
          load: true
          platforms: linux/amd64
          tags: ghcr.io/ardatan/graphql-mesh:test

      - name: Run E2E tests
        run: |
          cd ./docker
          chmod +x e2e-docker-test.sh
          ./e2e-docker-test.sh

      - name: Build and push multi-platform Docker image
        if: success()
        id: build-multi
        uses: docker/build-push-action@v6
        with:
          context: ./docker
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/ardatan/graphql-mesh:v1
            ghcr.io/ardatan/graphql-mesh:${{ github.sha }}

      - name: Log out of GitHub Container Registry
        run: docker logout ghcr.io
